kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.98.0.0/16"
  serviceSubnet: "10.99.0.0/16"
nodes:
  - role: control-plane
  - role: worker