kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6445
  podSubnet: "10.0.0.0/16"
  serviceSubnet: "10.1.0.0/16"
nodes:
  - role: control-plane
  - role: worker